# @credits https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_3_x/.github/workflows/build_and_release.yml
name: build 4.1.9.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3000
    defaults:
      run:
        shell: bash
    container: alpine:latest
    strategy:
      fail-fast: false
      matrix:
        # arch_type: [x86_64, armhf, armv7, aarch64]
        arch_type: ["mips"]
        boost_tag: ["-bt 1.68.0"]
        libtorrent_version: ["1.2"]
        icu_step_name: ["icu skipped"]
        build_tool: [""]
        qbittorrent_tag: ["-qt release-4.1.9.1"]
        include:
          - build_tool: "cmake"
            build_tool_name: "cmake-"

          - libtorrent_version: "1.2"
            libtorrent_tag: -lt libtorrent-1_1_14
            preview_release: false

    name: "${{ matrix.arch_type }}-${{ matrix.build_tool_name }}${{ matrix.icu_matrix_name }}libtorrent-v${{ matrix.libtorrent_version }}"

    env:
      build_dir: "qbt-build"
      qbt_build_tool: "${{ matrix.build_tool }}"
      qbt_cross_name: "${{ matrix.arch_type }}"
      libtorrent_version: "${{ matrix.libtorrent_version }}"
      name: "${{ matrix.arch_type }}-${{ matrix.build_tool_name }}${{ matrix.icu_matrix_name }}libtorrent-v${{ matrix.libtorrent_version }}"

    steps:
      - uses: actions/checkout@v2.3.4

      - run: apk add bash git
        shell: ash {0}

      - name: Bootstrap
        run: bash qbittorrent-nox-static.sh ${{ matrix.qbittorrent_tag }} ${{ matrix.libtorrent_tag }} -bs-a

      - name: Bootstrap release tag
        run: echo "release_tag=$(cat ${{ env.build_dir }}/release_info/tag.md)" >> $GITHUB_ENV

      - name: Bootstrap release title
        run: echo "release_title=$(cat ${{ env.build_dir }}/release_info/title.md)" >> $GITHUB_ENV

      - name: libexecinfo
        run: bash qbittorrent-nox-static.sh libexecinfo

      - name: zlib
        run: bash qbittorrent-nox-static.sh zlib

      - name: iconv
        run: bash qbittorrent-nox-static.sh iconv

      - name: ${{ matrix.icu_step_name }}
        run: "${{ matrix.with_icu }}"

      - name: openssl
        run: bash qbittorrent-nox-static.sh openssl

      - name: boost
        run: bash qbittorrent-nox-static.sh ${{matrix.boost_tag}} boost

      - name: libtorrent
        run: bash qbittorrent-nox-static.sh ${{ matrix.libtorrent_tag }} libtorrent

      - name: qtbase ${{ matrix.qt_with_icu }}
        run: bash qbittorrent-nox-static.sh ${{ matrix.qt_with_icu }} qtbase

      - name: qttools
        run: bash qbittorrent-nox-static.sh qttools

      - name: qbittorrent
        run: bash qbittorrent-nox-static.sh ${{ matrix.qbittorrent_tag }} qbittorrent

      - name: "Set release asset name"
        run: mv -f "${{ env.build_dir }}/completed/qbittorrent-nox" "${{ env.build_dir }}/completed/${{ matrix.arch_type }}-${{ matrix.build_tool_name }}${{ matrix.icu_matrix_name }}qbittorrent-nox"

      - name: "Create release - tag - assets"
        uses: ncipollo/release-action@v1
        with:
          prerelease: ${{ matrix.preview_release }}
          artifacts: "${{ env.build_dir }}/completed/${{ matrix.arch_type }}-${{ matrix.build_tool_name }}${{ matrix.icu_matrix_name }}qbittorrent-nox"
          replacesArtifacts: true
          tag: "${{ env.release_tag }}"
          name: "${{ env.release_title }}"
          bodyFile: "${{ env.build_dir }}/release_info/release.md"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive code coverage results
        if: env.qbt_build_tool == 'cmake'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.name }}-graphs
          path: ${{ env.build_dir }}/completed/*.png
