name: enhanced edition

on:
  workflow_dispatch:

# on:
#   push:
#     branches:
#       - "*"
#   pull_request:
#     branches:
#       - "*"
#   release:
#     types:
#       - released

jobs:
  # appimage:
  #   runs-on: ubuntu-16.04
  #   # Waiting https://github.com/linuxdeploy/linuxdeploy/issues/154 fixed
  #   # container: "ubuntu:16.04"
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Build AppImage
  #       run: sudo .github/workflows/build_appimage.sh
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: qBittorrent-Enhanced-Edition.AppImage
  #         path: |
  #           .github/workflows/qBittorrent-Enhanced-Edition.AppImage
  #           .github/workflows/qBittorrent-Enhanced-Edition.AppImage.zsync
  #     - name: Upload Github Assets
  #       if: startsWith(github.ref, 'refs/tags/')
  #       uses: svenstaro/upload-release-action@v2
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         file: ".github/workflows/qBittorrent-Enhanced-Edition.AppImage*"
  #         tag: ${{ github.ref }}
  #         overwrite: true
  #         file_glob: true

  # cross compile for some other platforms, like arm, mips, etc.
  cross-compile:
    runs-on: ubuntu-latest
    timeout-minutes: 3000
    container: "alpine:latest"
    strategy:
      fail-fast: false
      matrix:
        build_target: [mips, mipsel]
        include:
    name: "${{ matrix.build_target }}"
    env:
      QBITTORRENT_VERSION: "4.1.9.17"
      QBITTORRENT_ENHANCED: true
      UPX_COMPRESSION: false
      BUILD_TARGETS: "${{matrix.build_target}}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cross compile nox-static
        run: sh cross_build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: qbittorrent-nox_${{ matrix.cross_host }}_static
          path: |
            /tmp/qbittorrent-nox*
      - name: Upload Github Assets (Enhanced Edition)
        if: ${{ env.QBITTORRENT_ENHANCED == 'true' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "qbittorrent-nox_${{ matrix.cross_host }}_static.zip"
          tag: v${{ env.QBITTORRENT_VERSION }}-enhanced
          overwrite: true
      - name: Upload Github Assets
        if: ${{ env.QBITTORRENT_ENHANCED != 'true' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "qbittorrent-nox_${{ matrix.cross_host }}_static.zip"
          tag: v${{ env.QBITTORRENT_VERSION }}
          overwrite: true
